name: BlueMap-Signs
version: ${project.version}
main: net.mov51.blueMapSigns.BlueMapSigns
api-version: 1.16
depend: [BlueMap]
softdepend: []

commands:
  BlueMap-Signs:
    description: Manage the BlueMap Signs plugin

permissions:
  BlueMapSigns.CreateSet:
    description: Accsess to the base CreateMarkerSet subcommand
    default: true
  BlueMapSigns.DeleteSet:
    description: Accsess to the base DeleteMarkerSet subcommand
    default: true
  BlueMapSigns.ListSets:
    description: Accsess to the base ListMarkerSets subcommand
    default: true